nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: ["http://localhost:5173"] # ou autre URL du front
    allow_headers: ["Content-Type", "Authorization"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    max_age: 3600
  paths:
    "^/api/":
      origin_regex: true
      allow_origin: ["http://localhost:5173"]
      allow_headers: ["Content-Type", "Authorization"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      max_age: 3600
